// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkX2B8GDxr9ZCEDWRkD6m1fwT5N9jHOWc',
    appId: '1:778895779513:web:053a5b9e891ebd0366dd68',
    messagingSenderId: '778895779513',
    projectId: 'flutter-recette-october-2025-1',
    authDomain: 'flutter-recette-october-2025-1.firebaseapp.com',
    storageBucket: 'flutter-recette-october-2025-1.firebasestorage.app',
    measurementId: 'G-74WJ527V07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlU0vhgdrZKqfJYVxGIv8MjfMxmk9PgQ',
    appId: '1:778895779513:android:53e85a211663cfb466dd68',
    messagingSenderId: '778895779513',
    projectId: 'flutter-recette-october-2025-1',
    storageBucket: 'flutter-recette-october-2025-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZWQ7PLt7oDLBa_paZJfQpxXrIiu0EFA',
    appId: '1:778895779513:ios:77a4087aa3861cb866dd68',
    messagingSenderId: '778895779513',
    projectId: 'flutter-recette-october-2025-1',
    storageBucket: 'flutter-recette-october-2025-1.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZWQ7PLt7oDLBa_paZJfQpxXrIiu0EFA',
    appId: '1:778895779513:ios:77a4087aa3861cb866dd68',
    messagingSenderId: '778895779513',
    projectId: 'flutter-recette-october-2025-1',
    storageBucket: 'flutter-recette-october-2025-1.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkX2B8GDxr9ZCEDWRkD6m1fwT5N9jHOWc',
    appId: '1:778895779513:web:5ce4989fd9c4446766dd68',
    messagingSenderId: '778895779513',
    projectId: 'flutter-recette-october-2025-1',
    authDomain: 'flutter-recette-october-2025-1.firebaseapp.com',
    storageBucket: 'flutter-recette-october-2025-1.firebasestorage.app',
    measurementId: 'G-HWDCJ65YDV',
  );

}