// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmYg5-3PoffTGqShhVKrTsylxnHz1-XNs',
    appId: '1:378029160591:web:59be5d6b6a08a141db98fa',
    messagingSenderId: '378029160591',
    projectId: 'flutter-recette-october-2025',
    authDomain: 'flutter-recette-october-2025.firebaseapp.com',
    storageBucket: 'flutter-recette-october-2025.firebasestorage.app',
    measurementId: 'G-GRN6DHBLTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZSO1AggFvbbV-OSTw_BQw8QVkRJvZPc',
    appId: '1:378029160591:android:51e654757104ef02db98fa',
    messagingSenderId: '378029160591',
    projectId: 'flutter-recette-october-2025',
    storageBucket: 'flutter-recette-october-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG7e4WHWPEeEeTOMWQ46N4IMyglPebm4c',
    appId: '1:378029160591:ios:d4b3d96853cc3c9ddb98fa',
    messagingSenderId: '378029160591',
    projectId: 'flutter-recette-october-2025',
    storageBucket: 'flutter-recette-october-2025.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG7e4WHWPEeEeTOMWQ46N4IMyglPebm4c',
    appId: '1:378029160591:ios:d4b3d96853cc3c9ddb98fa',
    messagingSenderId: '378029160591',
    projectId: 'flutter-recette-october-2025',
    storageBucket: 'flutter-recette-october-2025.firebasestorage.app',
    iosBundleId: 'com.example.projetrecette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmYg5-3PoffTGqShhVKrTsylxnHz1-XNs',
    appId: '1:378029160591:web:406dd113a3e042d0db98fa',
    messagingSenderId: '378029160591',
    projectId: 'flutter-recette-october-2025',
    authDomain: 'flutter-recette-october-2025.firebaseapp.com',
    storageBucket: 'flutter-recette-october-2025.firebasestorage.app',
    measurementId: 'G-MSR6PKZHM2',
  );
}
